### ISSUE TITLE
Problem for use the branch 2.0 in cakephp 2.04

### ISSUE THREAD

**Issue by cpfarher** [webtechnick/CakePHP-FileUpload-Plugin#16]
Fatal error: Class 'FileUploadSettings' not found in /home/christian/public_html/unlweb/svn/webunl/app/Plugin/FileUpload/Controller/Component/FileUploadComponent.php on line 155

The file exist in config, may be de line:
App::import('Config', 'FileUpload.file_upload_settings');
fail, but i don´t know why?

**Comment by webtechnick** [comment]
The 2.0 branch is not even close to finished.  It was the first run through of the upgrade shell.  There is a lot more to be done.
