### ISSUE TITLE
Is the master branch suitable for use in CakePHP 2.0.6?

### ISSUE THREAD

**Issue by reypm** [webtechnick/CakePHP-FileUpload-Plugin#18]
Hi, I'm trying to use the master branch wht Cake 2.0.6 and get this error: Fatal error: Class 'Uploader' not found in /var/www/html/jobapp/app/Plugin/file_upload/models/behaviors/file_upload.php on line 55 

Any help?

**Comment by Artak81** [comment]
I have the same problem. I am use CakePHP 2.0.6.

**Comment by Artak81** [comment]
Hass podido solucionar esto? Si has podido di me porfa como has solucionado.

**Comment by Artak81** [comment]
He solucionado esta problema. El error desaparecio pero no me funcciono el plugin. Las carpetas tienen que ser en mayusculas y en algunos citios la letra "s" del final tiene que ser eliminado. Como por ejemplo "vendors" tiene que convertirse en "Vendor".

**Comment by reypm** [comment]
No, no lo he podido solucionar
