### ISSUE TITLE
Undefined index when deleting Model data

### ISSUE THREAD

**Issue by nfvs** [webtechnick/CakePHP-FileUpload-Plugin#2]
"Notice (8): Undefined index:  filename [CORE/plugins/file_upload/models/behaviors/file_upload.php, line 110]"

I have a Model "Document" with a belongsTo = 'Upload', and when I try to delete any document, I get this error.
The line before, "$data = $Model->read();" only reads the "Document" model and not the related "Upload" model, so thats why there's no filename index.

**Comment by webtechnick** [comment]
Why would it read the Document model?  Document doesn't actsAs FileUpload.FileUpload, the Upload does.  $Model should be Upload. 

I think you're attaching the behavior to the wrong model.

Hope that helps,
Nick

**Comment by nfvs** [comment]
I understand, but I wanted to use different upload folders for different models. That's why I defined another actAs in the Document model, although I understand I'm not supposed to. Everything worked, except delete.

Another (ideal?) option would be to alter Upload model's actAs['FileUpload.FileUpload']['uploadDir'] variable in the Document model. Is that possible?
