### ISSUE TITLE
Strict Errors

### ISSUE THREAD

**Issue by faizshukri** [webtechnick/CakePHP-FileUpload-Plugin#20]
Error when using FileUpload 6.1.1 with CakePHP 2.2.1

> Strict (2048): Declaration of FileUploadBehavior::setUp() should be compatible with ModelBehavior::setup(Model $model, $config = Array) [APP\Plugin\FileUpload\Model\Behavior\FileUploadBehavior.php, line 124]
> 
> Strict (2048): Declaration of FileUploadBehavior::beforeValidate() should be compatible with ModelBehavior::beforeValidate(Model $model) [APP\Plugin\FileUpload\Model\Behavior\FileUploadBehavior.php, line 124]
> 
> Strict (2048): Declaration of FileUploadBehavior::beforeSave() should be compatible with ModelBehavior::beforeSave(Model $model) [APP\Plugin\FileUpload\Model\Behavior\FileUploadBehavior.php, line 124]
> 
> Strict (2048): Declaration of FileUploadBehavior::beforeDelete() should be compatible with ModelBehavior::beforeDelete(Model $model, $cascade = true) [APP\Plugin\FileUpload\Model\Behavior\FileUploadBehavior.php, line 124]

found the solution in here - http://stackoverflow.com/questions/11678249/meio-upload-strict-erros

**Comment by gauravgupta123** [comment]
If you are looking to fix the error message, just open app/Config/core.php and change the 'Error' configuration to:

Configure::write('Error', array(
        'handler' => 'ErrorHandler::handleError',
        'level' => E_ALL & ~E_DEPRECATED & ~E_STRICT,
        'trace' => true
    ));

**Comment by mjw** [comment]
Except that wont fix them, that will just ignore them. My pull request (commit referenced above) will fix them.

**Comment by webtechnick** [comment]
This has been resolved in the lastest cakephp2.0 branch.  Thank you for your contribution.
