### ISSUE TITLE
Behavior options should be per model

### ISSUE THREAD

**Issue by nnc** [webtechnick/CakePHP-FileUpload-Plugin#4]
Take a look at [this page](http://book.cakephp.org/view/1073/Creating-Behaviors) in CakePHP book. In essence, in current code, if you have multiple models that use this behavior but with different options, all models will use the options that were passed to model that was last instantiated.

To avoid this problem, $this->options should actually be $this->options[$Model->alias]. Same goes for $this->Uploader I think.

**Comment by webtechnick** [comment]
You are correct.  This will go into the next version of FileUpload Plugin.

Thanks,
Nick

**Comment by nnc** [comment]
Any predictions on the release date for next version?

I fixed one more bug related to 'required' not being honored when file field is submitted, but empty.

I also had to add the following method to FileUploadBehavior:

```
function setFileUploadOption(&$Model, $key, $value) {
  $this->options[$Model->alias][$key] = $value;
  $this->Uploader[$Model->alias]->setOption($key, $value);
}
```

and setOption to Uploader class, of course.

I needed this to be able to change required option from controller. In this case, upload is required for 'add', but not required (nor allowed) for 'edit'. In 'edit', you can only change the category and label of the file, but you still need to be able to save the model via save() method.
I think this is common enough scenario to warrant inclusion of such feature.

I guess its about time for me to try that GitHub fork - edit - send pull request mambo-jumbo. Maybe during the weekend.

btw. Thanks for the plugin, it saved me a lot of time.

**Comment by with-impact** [comment]
Oye.  I just fought with FileUpload ALL day today because of this...  Very cool plugin...  nonetheless, I would advocate fixing this issue when you get the chance.

Thanks.

**Comment by nnc** [comment]
with-impact, you can pull the changes needed to overcome this issue from my fork now.

**Comment by webtechnick** [comment]
I've pulled in nnc's changes that close this issue.  I will be updating the documentation shortly.  

Thanks nnc.
