### ISSUE TITLE
Fatal Error received after setup

### ISSUE THREAD

**Issue by martinmike2** [webtechnick/CakePHP-FileUpload-Plugin#8]
I receive this error when I try to navigate to ../admin/uploads

Fatal error: Cannot redeclare class FileUploadSettings in C:\xampp\htdocs\zau\app\plugins\file_upload\config\file_upload_settings.php on line 2

**Comment by martinmike2** [comment]
Disregard, found my error.  For future reference, I had to declared in my AppController.

**Comment by y0ast** [comment]
I also have this issue.

Martin, could you explain in more detail what you did to fix it? 

"I had to declared in my AppController." does not help me much :(

**Comment by sigeje** [comment]
I solve this problem this night.
change line that contains App::import('Config', 'FileUpload.file_upload_settings'); with require_once(dirname(**FILE**) . DS . '..' . DS . '..' . DS . 'config' . DS . 'file_upload_settings.php');
that lines are exist in all file named file_upload.php in controller and view/helper directory

**Comment by vipulbishnoi** [comment]
Hello  Sigeje, your solution worked for me . Thanks dear.
vipul
